version: "3.2"
services:
  
  php:
    build: 
      context: './php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    user: '${USER_ID}:${GROUP_ID}'
    networks:
      - backend
    volumes:
      - ./apache/public_html/:/var/www/html/
    container_name: php

  apache:
    build:
      context: './apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/public_html/:/var/www/html/
    container_name: apache

  db:
     image: mariadb:${MARIADB_VERSION}
     environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
     networks:
      - backend
     restart: on-failure
     ports:
      - 3306:3306
     volumes:
      - ./mariadb/data:/var/lib/mysql
     container_name: mariadb

  adminer:
    image: adminer
    depends_on:
      - php
      - db
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    container_name: adminer

networks:
  frontend:
  backend:

volumes:
    data: